-- Preview multi-store data isolation. Additive columns plus a deterministic
-- backfill to the default/oldest store for every tenant. No rows are deleted.

ALTER TABLE orders ADD COLUMN store_id TEXT;
ALTER TABLE customers ADD COLUMN store_id TEXT;
ALTER TABLE coupons ADD COLUMN store_id TEXT;
ALTER TABLE products ADD COLUMN store_id TEXT;
ALTER TABLE product_variants ADD COLUMN store_id TEXT;
ALTER TABLE transactions ADD COLUMN store_id TEXT;
ALTER TABLE whatsapp_outbox ADD COLUMN store_id TEXT;
ALTER TABLE stock_log ADD COLUMN store_id TEXT;
ALTER TABLE suppliers ADD COLUMN store_id TEXT;
ALTER TABLE wallet_log ADD COLUMN store_id TEXT;
ALTER TABLE chat_messages ADD COLUMN store_id TEXT;
ALTER TABLE purchase_orders ADD COLUMN store_id TEXT;
ALTER TABLE goods_receipts ADD COLUMN store_id TEXT;
ALTER TABLE workflows ADD COLUMN store_id TEXT;
ALTER TABLE workflow_runs ADD COLUMN store_id TEXT;
ALTER TABLE audit_log ADD COLUMN store_id TEXT;
ALTER TABLE marketing_touchpoints ADD COLUMN store_id TEXT;
ALTER TABLE cod_reconciliations ADD COLUMN store_id TEXT;
ALTER TABLE cod_reconciliation_items ADD COLUMN store_id TEXT;
ALTER TABLE approval_requests ADD COLUMN store_id TEXT;
ALTER TABLE ai_action_requests ADD COLUMN store_id TEXT;
ALTER TABLE execution_jobs ADD COLUMN store_id TEXT;
ALTER TABLE notifications ADD COLUMN store_id TEXT;
ALTER TABLE conversations ADD COLUMN store_id TEXT;
ALTER TABLE channel_messages ADD COLUMN store_id TEXT;
ALTER TABLE marketing_campaigns ADD COLUMN store_id TEXT;
ALTER TABLE campaign_daily_metrics ADD COLUMN store_id TEXT;
ALTER TABLE pos_sessions ADD COLUMN store_id TEXT;
ALTER TABLE pos_sales ADD COLUMN store_id TEXT;
ALTER TABLE pos_sale_items ADD COLUMN store_id TEXT;
ALTER TABLE supplier_invoices ADD COLUMN store_id TEXT;
ALTER TABLE supplier_payments ADD COLUMN store_id TEXT;
ALTER TABLE purchase_returns ADD COLUMN store_id TEXT;

UPDATE orders SET store_id=(SELECT id FROM stores s WHERE s.client_id=orders.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE customers SET store_id=(SELECT id FROM stores s WHERE s.client_id=customers.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE coupons SET store_id=(SELECT id FROM stores s WHERE s.client_id=coupons.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE products SET store_id=(SELECT id FROM stores s WHERE s.client_id=products.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE product_variants SET store_id=(SELECT id FROM stores s WHERE s.client_id=product_variants.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE transactions SET store_id=(SELECT id FROM stores s WHERE s.client_id=transactions.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE whatsapp_outbox SET store_id=(SELECT id FROM stores s WHERE s.client_id=whatsapp_outbox.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE stock_log SET store_id=(SELECT id FROM stores s WHERE s.client_id=stock_log.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE suppliers SET store_id=(SELECT id FROM stores s WHERE s.client_id=suppliers.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE wallet_log SET store_id=(SELECT id FROM stores s WHERE s.client_id=wallet_log.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE chat_messages SET store_id=(SELECT id FROM stores s WHERE s.client_id=chat_messages.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE purchase_orders SET store_id=(SELECT id FROM stores s WHERE s.client_id=purchase_orders.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE goods_receipts SET store_id=(SELECT id FROM stores s WHERE s.client_id=goods_receipts.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE workflows SET store_id=(SELECT id FROM stores s WHERE s.client_id=workflows.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE workflow_runs SET store_id=(SELECT id FROM stores s WHERE s.client_id=workflow_runs.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE audit_log SET store_id=(SELECT id FROM stores s WHERE s.client_id=audit_log.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE marketing_touchpoints SET store_id=(SELECT id FROM stores s WHERE s.client_id=marketing_touchpoints.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE cod_reconciliations SET store_id=(SELECT id FROM stores s WHERE s.client_id=cod_reconciliations.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE cod_reconciliation_items SET store_id=(SELECT id FROM stores s WHERE s.client_id=cod_reconciliation_items.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE approval_requests SET store_id=(SELECT id FROM stores s WHERE s.client_id=approval_requests.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE ai_action_requests SET store_id=(SELECT id FROM stores s WHERE s.client_id=ai_action_requests.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE execution_jobs SET store_id=(SELECT id FROM stores s WHERE s.client_id=execution_jobs.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE notifications SET store_id=(SELECT id FROM stores s WHERE s.client_id=notifications.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE conversations SET store_id=(SELECT id FROM stores s WHERE s.client_id=conversations.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE channel_messages SET store_id=(SELECT id FROM stores s WHERE s.client_id=channel_messages.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE marketing_campaigns SET store_id=(SELECT id FROM stores s WHERE s.client_id=marketing_campaigns.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE campaign_daily_metrics SET store_id=(SELECT id FROM stores s WHERE s.client_id=campaign_daily_metrics.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE pos_sessions SET store_id=(SELECT id FROM stores s WHERE s.client_id=pos_sessions.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE pos_sales SET store_id=(SELECT id FROM stores s WHERE s.client_id=pos_sales.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE pos_sale_items SET store_id=(SELECT s.store_id FROM pos_sales s WHERE s.id=pos_sale_items.sale_id) WHERE store_id IS NULL;
UPDATE supplier_invoices SET store_id=(SELECT id FROM stores s WHERE s.client_id=supplier_invoices.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE supplier_payments SET store_id=(SELECT id FROM stores s WHERE s.client_id=supplier_payments.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;
UPDATE purchase_returns SET store_id=(SELECT id FROM stores s WHERE s.client_id=purchase_returns.client_id AND s.status='active' ORDER BY s.is_default DESC,s.created_at LIMIT 1) WHERE store_id IS NULL;

DROP INDEX IF EXISTS idx_customers_client_phone;
DROP INDEX IF EXISTS idx_coupons_client_code;
DROP INDEX IF EXISTS idx_campaign_external;
DROP INDEX IF EXISTS idx_conversation_external;
DROP INDEX IF EXISTS idx_channel_message_external;
DROP INDEX IF EXISTS idx_approval_idempotency;
DROP INDEX IF EXISTS idx_execution_jobs_idempotency;
CREATE UNIQUE INDEX IF NOT EXISTS idx_customers_store_phone ON customers(client_id,store_id,phone);
CREATE UNIQUE INDEX IF NOT EXISTS idx_coupons_store_code ON coupons(client_id,store_id,code);
CREATE UNIQUE INDEX IF NOT EXISTS idx_campaign_store_external ON marketing_campaigns(client_id,store_id,platform,external_campaign_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_conversation_store_external ON conversations(client_id,store_id,channel,external_thread_id);
CREATE UNIQUE INDEX IF NOT EXISTS idx_channel_message_store_external ON channel_messages(client_id,store_id,external_message_id) WHERE external_message_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_approval_store_idempotency ON approval_requests(client_id,store_id,idempotency_key) WHERE idempotency_key IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS idx_execution_store_idempotency ON execution_jobs(client_id,store_id,idempotency_key) WHERE idempotency_key IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_orders_store ON orders(client_id,store_id,date);
CREATE INDEX IF NOT EXISTS idx_products_store ON products(client_id,store_id,name);
CREATE INDEX IF NOT EXISTS idx_variants_store ON product_variants(client_id,store_id,product_id);
CREATE INDEX IF NOT EXISTS idx_stocklog_store ON stock_log(client_id,store_id,created_at);
CREATE INDEX IF NOT EXISTS idx_customers_store ON customers(client_id,store_id);
CREATE INDEX IF NOT EXISTS idx_suppliers_store ON suppliers(client_id,store_id);
CREATE INDEX IF NOT EXISTS idx_transactions_store ON transactions(client_id,store_id,date);
CREATE INDEX IF NOT EXISTS idx_po_store ON purchase_orders(client_id,store_id,order_date);
CREATE INDEX IF NOT EXISTS idx_pos_sessions_store ON pos_sessions(client_id,store_id,status,opened_at);
CREATE INDEX IF NOT EXISTS idx_pos_sales_store ON pos_sales(client_id,store_id,created_at);
CREATE INDEX IF NOT EXISTS idx_pos_items_store ON pos_sale_items(store_id,sale_id);
CREATE INDEX IF NOT EXISTS idx_campaigns_store ON marketing_campaigns(client_id,store_id,updated_at);
CREATE INDEX IF NOT EXISTS idx_campaign_metrics_store ON campaign_daily_metrics(client_id,store_id,metric_date);
CREATE INDEX IF NOT EXISTS idx_cod_store ON cod_reconciliations(client_id,store_id,created_at);
CREATE INDEX IF NOT EXISTS idx_workflows_store ON workflows(client_id,store_id,active);
CREATE INDEX IF NOT EXISTS idx_approvals_store ON approval_requests(client_id,store_id,status,requested_at);
CREATE INDEX IF NOT EXISTS idx_execution_store ON execution_jobs(client_id,store_id,status,available_at);
