import {readFile} from 'node:fs/promises';
const index=await readFile(new URL('../public/v2/index.html',import.meta.url),'utf8');
const ui=await readFile(new URL('../public/v2/modules-v19.js',import.meta.url),'utf8');
const worker=await readFile(new URL('../src/index-commerce-v20.js',import.meta.url),'utf8');
const must=(ok,msg)=>{if(!ok)throw new Error(msg)};
must(index.includes('data-view="readiness"'),'Readiness navigation missing');
must(index.includes('/v2/modules-v19.js'),'Readiness UI asset missing');
must(ui.includes('/api/release/readiness'),'Readiness UI must call release readiness API');
for(const marker of ['Code Ready','Integrations Ready','SESSION_SECRET','INTEGRATION_ENCRYPTION_KEY','Preview Environment'])must(ui.includes(marker),`Readiness UI missing ${marker}`);
for(const marker of ["'/api/release/readiness'",'codeReady','integrationsReady','previewEnvironment'])must(worker.includes(marker),`Readiness backend missing ${marker}`);
console.log('Release readiness UI/backend contract passed.');
