import {readFile} from 'node:fs/promises';
import {execFileSync} from 'node:child_process';
import {fileURLToPath} from 'node:url';
const index=await readFile(new URL('../public/v2/index.html',import.meta.url),'utf8');
const ui=await readFile(new URL('../public/v2/modules-v19.js',import.meta.url),'utf8');
const worker=await readFile(new URL('../src/index-commerce-v20.js',import.meta.url),'utf8');
const dashboardUxUrl=new URL('../public/v2/modules-v122-dashboard-experience.js',import.meta.url);
const dashboardUx=await readFile(dashboardUxUrl,'utf8');
const previewEntry=await readFile(new URL('../src/index-commerce-v38.js',import.meta.url),'utf8');
const productionEntry=await readFile(new URL('../src/index-production-mobile-update.js',import.meta.url),'utf8');
const must=(ok,msg)=>{if(!ok)throw new Error(msg)};
must(index.includes('data-view="readiness"'),'Readiness navigation missing');
must(index.includes('/v2/modules-v19.js'),'Readiness UI asset missing');
must(ui.includes('/api/release/readiness'),'Readiness UI must call release readiness API');
for(const marker of ['Code Ready','Integrations Ready','SESSION_SECRET','INTEGRATION_ENCRYPTION_KEY','Preview Environment'])must(ui.includes(marker),`Readiness UI missing ${marker}`);
for(const marker of ["'/api/release/readiness'",'codeReady','integrationsReady','previewEnvironment','integrationEncryptionKeySource','preview_derived'])must(worker.includes(marker),`Readiness backend missing ${marker}`);
must(ui.includes('مفتاح Preview معزول مشتق من SESSION_SECRET'),'Readiness UI must disclose the Preview-derived encryption key source');
execFileSync(process.execPath,['--check',fileURLToPath(dashboardUxUrl)],{stdio:'pipe'});
for(const marker of ['EXECUTIVE PULSE','Commerce Command Center','dash-x-executive','dash-x-delta-grid','changeMeta','sectionOrder','actualOrderCost','dash-campaign-strip','dash-ai-ad-kpis'])must(dashboardUx.includes(marker),`Dashboard v122 UX missing ${marker}`);
must(dashboardUx.includes("['overview','trend','finance','ads','rates','provinces','ai']"),'Dashboard v122 must preserve the intended analytical hierarchy.');
must(dashboardUx.includes(".dash-section-actions .dash-period-control")&&dashboardUx.includes(".dash-drill-head>.dash-period-chip"),'Dashboard v122 must remove duplicate period controls.');
must(dashboardUx.includes("hidden=['actualOrderCost','margin','adSpend']"),'Dashboard v122 must remove repeated top-level KPI cards.');
must(previewEntry.includes('/v2/modules-v122-dashboard-experience.js?v=122.0'),'Preview must inject dashboard v122 UX.');
must(productionEntry.includes('/v2/modules-v122-dashboard-experience.js?v=122.0'),'Production must inject dashboard v122 UX.');
console.log('Release readiness and dashboard v122 UI contracts passed.');
