const base = (process.argv[2] || '').replace(/\/$/, '');
if (!base) throw new Error('Usage: node scripts/smoke-test.mjs <base-url>');
const PROPAGATION_ATTEMPTS=12;
const PROPAGATION_DELAY_MS=5000;
async function fetchWithRetry(path,options={}) {let lastError;for (let attempt=1;attempt<=6;attempt+=1){try{return await fetch(`${base}${path}`,{redirect:'follow',...options});}catch(error){lastError=error;if(attempt<6)await new Promise(r=>setTimeout(r,attempt*2000));}}throw lastError;}
async function eventually(path,validate){let lastError;for(let attempt=1;attempt<=PROPAGATION_ATTEMPTS;attempt+=1){try{const response=await fetchWithRetry(path);const body=await response.text();validate(body,response);return response;}catch(error){lastError=error;if(attempt<PROPAGATION_ATTEMPTS)await new Promise(r=>setTimeout(r,PROPAGATION_DELAY_MS));}}throw lastError;}
async function check(path, validate) {await eventually(path,(body,response)=>{if(!response.ok)throw new Error(`${path} returned ${response.status}: ${body}`);validate(body,response);});console.log(`Smoke check passed: ${path}`);}
async function checkProtected(path){const response=await eventually(path,(body,current)=>{if(![401,403].includes(current.status))throw new Error(`${path} must reject unauthenticated access; got ${current.status}: ${body}`);if(/SESSION_SECRET/i.test(body))throw new Error(`${path} leaked session configuration details`);});console.log(`Protected-route check passed: ${path} -> ${response.status}`);}
await check('/healthz',(body)=>{const data=JSON.parse(body);if(data.ok!==true||data.environment!=='preview'||data.database!=='reachable')throw new Error(`Unexpected health response: ${body}`);});
await check('/api/preview/version',(body)=>{const data=JSON.parse(body);if(data.build!=='preview-v34-2026-08-31-minute-meta-exact-dedupe'||data.entrypoint!=='index-commerce-v34.js'||data.environment!=='preview')throw new Error(`Unexpected deployed build: ${body}`);});
await check('/v2/',(body,response)=>{if(!body.trim())throw new Error('/v2/ returned an empty response');if(!/text\/html/i.test(response.headers.get('content-type')||''))throw new Error('/v2/ must return HTML');for(const marker of ['viewport-fit=cover','kun-v7.css','kun-v8.css','kun-v9.css','kun-v10.css','kun-v11.css','kun-v12.css','kun-v13.css','family=Cairo','client-context-v23.js','performance-core-v52.js','modules-v17.js','modules-v18.js','modules-v19.js','modules-v20.js','modules-v21.js','modules-v22.js','modules-v23-core.js','modules-v23-admin.js?v=23.3','modules-v23-create.js','modules-v23-data.js','modules-v24-team.js','modules-v31-customer-service.js','modules-v33-dashboard.js','modules-v34-dashboard-ai.js','modules-v35-order-import.js','modules-v36-accounting.js','modules-v43-product-catalog.js','modules-v44-customer-service-order-edit.js','modules-v47-post-shipping.js','modules-v48-ad-expert.js','data-view="dashboard">الداشبورد','data-view="onboarding"','data-view="readiness"','data-view="stores"','data-view="store-access"','data-view="customer-service"','data-view="post-shipping"','data-view="access"','data-view="ops"','data-view="control"','data-view="integrations"','data-view="wallet"','data-view="admin-clients"','data-view="ad-studio"','data-view="settings"','data-theme="light"'])if(!body.includes(marker))throw new Error(`/v2/ missing marker: ${marker}`);if(body.includes('modules-v45-post-shipping.js'))throw new Error('/v2/ must not load superseded modules-v45-post-shipping.js');});
await check('/preview-admin-recovery.html',(body)=>{for(const marker of ['استعادة أدمن Preview','/api/preview-admin-recovery','كود الاستعادة'])if(!body.includes(marker))throw new Error(`preview-admin-recovery.html missing: ${marker}`);});
await check('/v2/kun-v7.css',(body)=>{for(const marker of ['body[data-theme="gray"]','body[data-theme="dark"]','@media(max-width:820px)','@media(max-width:560px)','prefers-reduced-motion'])if(!body.includes(marker))throw new Error(`kun-v7.css missing: ${marker}`);});
await check('/v2/kun-v9.css',(body)=>{for(const marker of ['.v27-order-actions','.v27-admin-only','.v27-topup'])if(!body.includes(marker))throw new Error(`kun-v9.css missing marker: ${marker}`);});
await check('/v2/kun-v10.css',(body)=>{for(const marker of ['.cs-board','.cs-deferred','.cs-returned-today','.cs-modal-back','@media(max-width:700px)'])if(!body.includes(marker))throw new Error(`kun-v10.css missing marker: ${marker}`);});
await check('/v2/kun-v11.css',(body)=>{for(const marker of ['.dash-kpis','.dash-drilldown','.dash-ad-grid','.dash-ai-grid','.dash-bars','@media(max-width:820px)','@media(max-width:390px)','body[data-theme="dark"]'])if(!body.includes(marker))throw new Error(`kun-v11.css missing marker: ${marker}`);});
await check('/v2/kun-v12.css',(body)=>{for(const marker of ['.dash-updated','.dash-trend-tabs','.dash-province-list','.dash-refreshing','prefers-reduced-motion'])if(!body.includes(marker))throw new Error(`kun-v12.css missing marker: ${marker}`);});
await check('/v2/kun-v13.css',(body)=>{for(const marker of ['#0D47A1','#26B34A','#F5F7FA','#64748B','#0F172A','.dash-ai-analysis','.dash-ai-ad-table'])if(!body.includes(marker))throw new Error(`kun-v13.css missing marker: ${marker}`);});
await check('/v2/performance-core-v52.js',(body)=>{for(const marker of ['KunPerformanceCore','/api/me','/api/navigation-access','requestIdleCallback'])if(!body.includes(marker))throw new Error(`performance-core-v52.js missing: ${marker}`);});
await check('/v2/modules-v16.js',(body)=>{for(const marker of ['/api/integrations/readiness','missingSecrets','مركز التكاملات'])if(!body.includes(marker))throw new Error(`modules-v16.js missing: ${marker}`);});
await check('/v2/modules-v17.js',(body)=>{for(const marker of ['/api/stores','/api/ai/insights/generate','/api/ai-actions','المتاجر والفروع'])if(!body.includes(marker))throw new Error(`modules-v17.js missing: ${marker}`);});
await check('/v2/modules-v18.js',(body)=>{for(const marker of ['/api/onboarding/status','/api/team-members','/api/store-access','صلاحيات الفروع'])if(!body.includes(marker))throw new Error(`modules-v18.js missing: ${marker}`);});
await check('/v2/modules-v19.js',(body)=>{for(const marker of ['/api/release/readiness','Code Ready','Integrations Ready','INTEGRATION_ENCRYPTION_KEY'])if(!body.includes(marker))throw new Error(`modules-v19.js missing: ${marker}`);});
await check('/v2/modules-v20.js',(body)=>{for(const marker of ['/api/orders','/api/customers','/api/products','/api/suppliers','/stock/add','data-v20-theme'])if(!body.includes(marker))throw new Error(`modules-v20.js missing: ${marker}`);});
await check('/v2/modules-v21.js',(body)=>{for(const marker of ['/api/pos/sales','/api/workflows','/api/campaigns','/api/procurement/invoices','qaVariantCreate','qaOrderSave'])if(!body.includes(marker))throw new Error(`modules-v21.js missing: ${marker}`);});
await check('/v2/modules-v22.js',(body)=>{for(const marker of ['/api/wallet','/api/admin/clients','/api/marketing/performance','/api/ai/business-brief','/api/ad-studio/drafts'])if(!body.includes(marker))throw new Error(`modules-v22.js missing: ${marker}`);});
await check('/v2/modules-v23-core.js',(body)=>{for(const marker of ['KunActionsV23','dataset.v23Actions','K.scope'])if(!body.includes(marker))throw new Error(`modules-v23-core.js missing: ${marker}`);});
await check('/v2/modules-v23-admin.js',(body)=>{for(const marker of ['v23CreateClient','/api/admin/clients','reset-owner-password','v23CreditWallet','v23SaveOrderFee','بدون حد أقصى'])if(!body.includes(marker))throw new Error(`modules-v23-admin.js missing: ${marker}`);});
await check('/v2/modules-v23-create.js',(body)=>{for(const marker of ['openCreateOrder','openCreateCustomer','openCreateProduct','openStockAdjust'])if(!body.includes(marker))throw new Error(`modules-v23-create.js missing: ${marker}`);});
await check('/v2/modules-v23-data.js',(body)=>{for(const marker of ['saveOrderView','exportCustomers','openProductsIO','stopImmediatePropagation'])if(!body.includes(marker))throw new Error(`modules-v23-data.js missing: ${marker}`);});
await check('/v2/modules-v24-team.js',(body)=>{for(const marker of ['/api/team-role-catalog','/api/team-members','v28AddMember','v28CreateMember','v28SaveStores','v28ResetPassword','v28DeleteMember','KunTeamV28'])if(!body.includes(marker))throw new Error(`modules-v24-team.js missing: ${marker}`);});
await check('/v2/modules-v31-customer-service.js',(body)=>{for(const marker of ['/api/customer-service','الطلبات المؤجلة','سجل الأوردر','href="tel:','https://wa.me/','ملاحظة داخلية لخدمة العملاء'])if(!body.includes(marker))throw new Error(`modules-v31-customer-service.js missing: ${marker}`);if(body.includes('حذف'))throw new Error('Customer Service UI must not expose deletion');});
await check('/v2/modules-v33-dashboard.js',(body)=>{for(const marker of ['/api/dashboard','تكلفة الطلب الفعلية','الإيرادات المتوقعة','الأرباح المتوقعة','نتائج الإعلانات بالتفصيل','أفضل المحافظات للشحن','أهم توصيات kun AI','أهم مؤشرات البيزنس وطريقة سريانه','data-dash-reload','reloadSection','data-dash-trend','data-dash-kpi'])if(!body.includes(marker))throw new Error(`modules-v33-dashboard.js missing: ${marker}`);});
await check('/v2/modules-v34-dashboard-ai.js',(body)=>{for(const marker of ['/api/ai/business-brief','تحليل الإعلانات بالـAI','Breakdown كامل للحملات','CPP فعلي','CPP مؤكد','CPP مسلم','Real ROAS','KunDashboardAI34'])if(!body.includes(marker))throw new Error(`modules-v34-dashboard-ai.js missing: ${marker}`);});
await check('/v2/modules-v36-accounting.js',(body)=>{for(const marker of ['الحسابات','/api/accounting/overview','/api/accounting/entries','نسبة الإدارة الآلية','إعدادات نسبة الإدارة'])if(!body.includes(marker))throw new Error(`modules-v36-accounting.js missing: ${marker}`);});
await check('/v2/modules-v43-product-catalog.js',(body)=>{for(const marker of ['تكوين المتغيرات تلقائيًا','المخزون حسب اللون والمقاس','optionValues','/api/catalog/products'])if(!body.includes(marker))throw new Error(`modules-v43-product-catalog.js missing: ${marker}`);});
await check('/v2/modules-v44-customer-service-order-edit.js',(body)=>{for(const marker of ['تعديل الطلب','معدّل','/edit','منتجات الطلب'])if(!body.includes(marker))throw new Error(`modules-v44-customer-service-order-edit.js missing: ${marker}`);});
await check('/v2/modules-v47-post-shipping.js',(body)=>{for(const marker of ['خدمات ما بعد الشحن','جاري الشحن','تم الشحن','جاري التحصيل','تم التحصيل','المبلغ المستلم من شركة الشحن','/collect'])if(!body.includes(marker))throw new Error(`modules-v47-post-shipping.js missing: ${marker}`);});
await check('/v2/modules-v48-ad-expert.js',(body)=>{for(const marker of ['تحليل الحملات الإعلانية','تحليل المجموعات الإعلانية','تحليل الإعلانات','قراءة خبير الإعلانات','/api/integrations/meta-ads/expert-analysis','/api/integrations/meta-ads/expert-sync','Score','ROAS Trend','CTR Trend','التقييم'])if(!body.includes(marker))throw new Error(`modules-v48-ad-expert.js missing: ${marker}`);});
for(const path of ['/api/release/readiness','/api/stores','/api/onboarding/status','/api/team-role-catalog','/api/team-members','/api/integrations/readiness','/api/approvals','/api/audit-log','/api/wallet','/api/marketing/performance','/api/ai/business-brief','/api/ad-studio/drafts','/api/customer-service','/api/post-shipping','/api/catalog/products','/api/dashboard','/api/accounting/overview','/api/integrations/meta-ads/expert-analysis'])await checkProtected(path);
const sessionResponse=await fetchWithRetry('/api/me');const sessionBody=await sessionResponse.text();if(![200,401].includes(sessionResponse.status)||/SESSION_SECRET/i.test(sessionBody))throw new Error(`Session configuration smoke check failed: ${sessionResponse.status} ${sessionBody}`);console.log('Smoke check passed: SESSION_SECRET is configured');
