const base = (process.argv[2] || '').replace(/\/$/, '');
if (!base) throw new Error('Usage: node scripts/smoke-test.mjs <base-url>');
async function fetchWithRetry(path) {let lastError;for (let attempt=1;attempt<=6;attempt+=1){try{return await fetch(`${base}${path}`,{redirect:'follow'});}catch(error){lastError=error;if(attempt<6)await new Promise(r=>setTimeout(r,attempt*2000));}}throw lastError;}
async function check(path, validate) {const response=await fetchWithRetry(path);const body=await response.text();if(!response.ok)throw new Error(`${path} returned ${response.status}: ${body}`);validate(body,response);console.log(`Smoke check passed: ${path}`);}
await check('/healthz',(body)=>{const data=JSON.parse(body);if(data.ok!==true||data.environment!=='preview'||data.database!=='reachable')throw new Error(`Unexpected health response: ${body}`);});
await check('/v2/',(body)=>{if(!body.trim())throw new Error('/v2/ returned an empty response');for(const marker of ['viewport-fit=cover','kun-v7.css','modules-v7.js','modules-v10.js','modules-v11.js','modules-v12.js','data-view="ops"','data-view="control"','data-view="inbox"','data-view="campaigns"','data-theme="light"'])if(!body.includes(marker))throw new Error(`/v2/ missing marker: ${marker}`);});
await check('/v2/kun-v7.css',(body)=>{for(const marker of ['body[data-theme="gray"]','body[data-theme="dark"]','@media(max-width:820px)','@media(max-width:560px)','prefers-reduced-motion'])if(!body.includes(marker))throw new Error(`kun-v7.css missing: ${marker}`);});
await check('/v2/modules-v7.js',(body)=>{for(const marker of ["['light','gray','dark']",'mobileMenuBtn','kun-theme'])if(!body.includes(marker))throw new Error(`modules-v7.js missing: ${marker}`);});
await check('/v2/modules-v10.js',(body)=>{for(const marker of ['/api/system-status','/api/execution-jobs','/api/notifications'])if(!body.includes(marker))throw new Error(`modules-v10.js missing: ${marker}`);});
await check('/v2/modules-v11.js',(body)=>{for(const marker of ['/api/tenant/overview','/api/store-connections','/api/support-tickets'])if(!body.includes(marker))throw new Error(`modules-v11.js missing: ${marker}`);});
await check('/v2/modules-v12.js',(body)=>{for(const marker of ['/api/inbox/conversations','/api/campaigns/summary'])if(!body.includes(marker))throw new Error(`modules-v12.js missing: ${marker}`);});
const sessionResponse=await fetchWithRetry('/api/me');const sessionBody=await sessionResponse.text();if(![200,401].includes(sessionResponse.status)||/SESSION_SECRET/i.test(sessionBody))throw new Error(`Session configuration smoke check failed: ${sessionResponse.status} ${sessionBody}`);console.log('Smoke check passed: SESSION_SECRET is configured');
