const base = (process.argv[2] || '').replace(/\/$/, '');
if (!base) throw new Error('Usage: node scripts/smoke-test.mjs <base-url>');
const PROPAGATION_ATTEMPTS=12;
const PROPAGATION_DELAY_MS=5000;
async function fetchWithRetry(path,options={}) {let lastError;for (let attempt=1;attempt<=6;attempt+=1){try{return await fetch(`${base}${path}`,{redirect:'follow',...options});}catch(error){lastError=error;if(attempt<6)await new Promise(r=>setTimeout(r,attempt*2000));}}throw lastError;}
async function eventually(path,validate){let lastError;for(let attempt=1;attempt<=PROPAGATION_ATTEMPTS;attempt+=1){try{const response=await fetchWithRetry(path);const body=await response.text();validate(body,response);return response;}catch(error){lastError=error;if(attempt<PROPAGATION_ATTEMPTS)await new Promise(r=>setTimeout(r,PROPAGATION_DELAY_MS));}}throw lastError;}
async function check(path, validate) {await eventually(path,(body,response)=>{if(!response.ok)throw new Error(`${path} returned ${response.status}: ${body}`);validate(body,response);});console.log(`Smoke check passed: ${path}`);}
async function checkProtected(path){const response=await eventually(path,(body,current)=>{if(![401,403].includes(current.status))throw new Error(`${path} must reject unauthenticated access; got ${current.status}: ${body}`);if(/SESSION_SECRET/i.test(body))throw new Error(`${path} leaked session configuration details`);});console.log(`Protected-route check passed: ${path} -> ${response.status}`);}
await check('/healthz',(body)=>{const data=JSON.parse(body);if(data.ok!==true||data.environment!=='preview'||data.database!=='reachable')throw new Error(`Unexpected health response: ${body}`);});
await check('/api/preview/version',(body)=>{const data=JSON.parse(body);if(data.build!=='preview-v27-2026-08-27'||data.entrypoint!=='index-commerce-v27.js'||data.environment!=='preview')throw new Error(`Unexpected deployed build: ${body}`);});
await check('/v2/',(body,response)=>{if(!body.trim())throw new Error('/v2/ returned an empty response');if(!/text\/html/i.test(response.headers.get('content-type')||''))throw new Error('/v2/ must return HTML');for(const marker of ['viewport-fit=cover','kun-v7.css','kun-v8.css','kun-v9.css','client-context-v23.js','modules-v17.js','modules-v18.js','modules-v19.js','modules-v20.js','modules-v21.js','modules-v22.js','data-view="onboarding"','data-view="readiness"','data-view="stores"','data-view="store-access"','data-view="ops"','data-view="control"','data-view="integrations"','data-view="wallet"','data-view="admin-clients"','data-view="ad-studio"','data-view="settings"','data-theme="light"'])if(!body.includes(marker))throw new Error(`/v2/ missing marker: ${marker}`);});
await check('/preview-admin-recovery.html',(body)=>{for(const marker of ['استعادة أدمن Preview','/api/preview-admin-recovery','كود الاستعادة'])if(!body.includes(marker))throw new Error(`preview-admin-recovery.html missing: ${marker}`);});
await check('/v2/kun-v7.css',(body)=>{for(const marker of ['body[data-theme="gray"]','body[data-theme="dark"]','@media(max-width:820px)','@media(max-width:560px)','prefers-reduced-motion'])if(!body.includes(marker))throw new Error(`kun-v7.css missing: ${marker}`);});
await check('/v2/kun-v9.css',(body)=>{for(const marker of ['.v27-order-actions','.v27-admin-client','.v27-wallet'])if(!body.includes(marker))throw new Error(`kun-v9.css missing marker: ${marker}`);});
await check('/v2/modules-v16.js',(body)=>{for(const marker of ['/api/integrations/readiness','missingSecrets','مركز التكاملات'])if(!body.includes(marker))throw new Error(`modules-v16.js missing: ${marker}`);});
await check('/v2/modules-v17.js',(body)=>{for(const marker of ['/api/stores','/api/ai/insights/generate','/api/ai-actions','المتاجر والفروع'])if(!body.includes(marker))throw new Error(`modules-v17.js missing: ${marker}`);});
await check('/v2/modules-v18.js',(body)=>{for(const marker of ['/api/onboarding/status','/api/team-members','/api/store-access','صلاحيات الفروع'])if(!body.includes(marker))throw new Error(`modules-v18.js missing: ${marker}`);});
await check('/v2/modules-v19.js',(body)=>{for(const marker of ['/api/release/readiness','Code Ready','Integrations Ready','INTEGRATION_ENCRYPTION_KEY'])if(!body.includes(marker))throw new Error(`modules-v19.js missing: ${marker}`);});
await check('/v2/modules-v20.js',(body)=>{for(const marker of ['/api/orders','/api/customers','/api/products','/api/suppliers','/stock/add','data-v20-theme'])if(!body.includes(marker))throw new Error(`modules-v20.js missing: ${marker}`);});
await check('/v2/modules-v21.js',(body)=>{for(const marker of ['/api/pos/sales','/api/workflows','/api/campaigns','/api/procurement/invoices','qaVariantCreate','qaOrderSave'])if(!body.includes(marker))throw new Error(`modules-v21.js missing: ${marker}`);});
await check('/v2/modules-v22.js',(body)=>{for(const marker of ['/api/wallet','/api/admin/clients','/api/marketing/performance','/api/ai/business-brief','/api/ad-studio/drafts'])if(!body.includes(marker))throw new Error(`modules-v22.js missing: ${marker}`);});
for(const path of ['/api/release/readiness','/api/stores','/api/onboarding/status','/api/integrations/readiness','/api/approvals','/api/audit-log','/api/wallet','/api/marketing/performance','/api/ai/business-brief','/api/ad-studio/drafts'])await checkProtected(path);
const sessionResponse=await fetchWithRetry('/api/me');const sessionBody=await sessionResponse.text();if(![200,401].includes(sessionResponse.status)||/SESSION_SECRET/i.test(sessionBody))throw new Error(`Session configuration smoke check failed: ${sessionResponse.status} ${sessionBody}`);console.log('Smoke check passed: SESSION_SECRET is configured');
