const now=()=>new Date().toISOString();
const id=p=>`${p}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;
const parse=s=>{try{return JSON.parse(s||'{}')}catch{return {}}};
async function note(env,clientId,title,body,severity='info',entityType=null,entityId=null){await env.DB.prepare(`INSERT INTO notifications (id,client_id,type,title,body,severity,entity_type,entity_id,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).bind(id('NTF'),clientId,'execution',title,body||'',severity,entityType,entityId,now()).run();}
async function audit(env,job,status,meta={}){await env.DB.prepare(`INSERT INTO audit_log (id,client_id,actor_user_id,actor_email,action,entity_type,entity_id,metadata_json,created_at) VALUES (?,?,?,?,?,?,?,?,?)`).bind(id('AUD'),job.client_id,null,'system@kun-online',`execution.${status}`,'execution_job',job.id,JSON.stringify(meta),now()).run();}
async function runAction(env,job){const p=parse(job.payload_json);switch(job.action_type){
  case 'add_tag': {if(!p.customerId||!p.tag)throw new Error('customerId/tag required');const row=await env.DB.prepare('SELECT tags FROM customers WHERE id=? AND client_id=?').bind(p.customerId,job.client_id).first();if(!row)throw new Error('customer_not_found');let tags=[];try{tags=JSON.parse(row.tags||'[]')}catch{}if(!tags.includes(p.tag))tags.push(String(p.tag));await env.DB.prepare('UPDATE customers SET tags=? WHERE id=? AND client_id=?').bind(JSON.stringify(tags),p.customerId,job.client_id).run();return {customerId:p.customerId,tag:p.tag};}
  case 'add_note': {if(!p.customerId||!p.note)throw new Error('customerId/note required');const row=await env.DB.prepare('SELECT note FROM customers WHERE id=? AND client_id=?').bind(p.customerId,job.client_id).first();if(!row)throw new Error('customer_not_found');const next=[row.note,String(p.note)].filter(Boolean).join('\n');await env.DB.prepare('UPDATE customers SET note=? WHERE id=? AND client_id=?').bind(next,p.customerId,job.client_id).run();return {customerId:p.customerId};}
  case 'assign_agent': {if(!p.conversationId||!p.agent)throw new Error('conversationId/agent required');await env.DB.prepare('UPDATE conversations SET assigned_to=?,updated_at=? WHERE id=? AND client_id=?').bind(String(p.agent),now(),p.conversationId,job.client_id).run();return {conversationId:p.conversationId,agent:p.agent};}
  case 'notify_team': {await note(env,job.client_id,p.title||'تنبيه أتمتة',p.body||p.message||'',p.severity||'info',p.entityType||null,p.entityId||null);return {notified:true};}
  case 'send_whatsapp': {if(!p.orderId||!p.phone||!p.message)throw new Error('orderId/phone/message required');const mid=id('WA');await env.DB.prepare(`INSERT INTO whatsapp_outbox (id,client_id,order_id,phone,message,kind,status,created_at) VALUES (?,?,?,?,?,?,?,?)`).bind(mid,job.client_id,p.orderId,p.phone,p.message,p.kind||'automation','pending',now()).run();return {outboxId:mid};}
  default: throw new Error(`adapter_not_configured:${job.action_type}`);
}}
export async function processExecutionJobs(env,{limit=20}={}){const ts=now();const {results}=await env.DB.prepare(`SELECT * FROM execution_jobs WHERE status IN ('queued','failed') AND available_at<=? ORDER BY available_at ASC LIMIT ?`).bind(ts,Math.max(1,Math.min(50,limit))).all();const outcomes=[];for(const job of results||[]){const started=now();const claim=await env.DB.prepare("UPDATE execution_jobs SET status='running',attempts=attempts+1,started_at=?,updated_at=? WHERE id=? AND status IN ('queued','failed')").bind(started,started,job.id).run();if(claim?.meta?.changes===0)continue;try{const result=await runAction(env,job);const done=now();await env.DB.prepare("UPDATE execution_jobs SET status='completed',finished_at=?,last_error=NULL,updated_at=? WHERE id=?").bind(done,done,job.id).run();await audit(env,job,'completed',{result});outcomes.push({id:job.id,status:'completed'});}catch(e){const attempts=Number(job.attempts||0)+1,max=Number(job.max_attempts||3);const dead=attempts>=max,status=dead?'dead_letter':'failed';const delayMinutes=Math.min(60,Math.pow(2,Math.max(0,attempts-1)));const available=new Date(Date.now()+delayMinutes*60000).toISOString();const updated=now();await env.DB.prepare('UPDATE execution_jobs SET status=?,last_error=?,available_at=?,finished_at=?,updated_at=? WHERE id=?').bind(status,String(e.message||e),available,dead?updated:null,updated,job.id).run();await audit(env,job,status,{error:String(e.message||e),attempts,nextAttemptAt:dead?null:available});if(dead)await note(env,job.client_id,'تعذر تنفيذ إجراء بعد عدة محاولات',`${job.action_type}: ${String(e.message||e)}`,'danger','execution_job',job.id);outcomes.push({id:job.id,status,error:String(e.message||e)});}}
return outcomes;}
