const OUTBOUND_STATES=new Set(['shipped','signed','collected']);
const clean=v=>String(v??'').trim();
const now=()=>new Date().toISOString();
const fail=(message,status=400,code='INVENTORY_BATCH_ERROR')=>{throw Object.assign(new Error(message),{status,code});};
const actorName=actor=>clean(actor?.email||actor?.name||actor?.role||actor?.id||actor?.uid)||'system';
function validDate(value){const v=clean(value);if(!/^\d{4}-\d{2}-\d{2}$/.test(v)||Number.isNaN(Date.parse(`${v}T00:00:00Z`)))fail('تاريخ إضافة المخزون غير صحيح',400,'STOCK_BATCH_DATE_INVALID');return v;}
async function refreshBatchStatus(env,batchId){
  const row=await env.DB.prepare('SELECT COALESCE(SUM(remaining_qty),0) remaining FROM inventory_batch_items WHERE batch_id=?').bind(batchId).first();
  const status=Number(row?.remaining||0)>0?'active':'depleted';
  await env.DB.prepare('UPDATE inventory_batches SET status=? WHERE id=?').bind(status,batchId).run();
  return status;
}
export async function listInventoryBatches(env,{clientId,storeId=null,activeOnly=false}={}){
  if(!clientId)fail('محتاج clientId',400,'CLIENT_ID_REQUIRED');
  const where=['b.client_id=?'],binds=[clientId];if(storeId){where.push('b.store_id=?');binds.push(storeId);}
  let sql=`SELECT b.id,b.client_id,b.store_id,b.name,b.stock_date,b.note,b.status,b.created_at,b.created_by,
    COALESCE(SUM(i.initial_qty),0) total_initial,COALESCE(SUM(i.remaining_qty),0) total_remaining
    FROM inventory_batches b LEFT JOIN inventory_batch_items i ON i.batch_id=b.id
    WHERE ${where.join(' AND ')} GROUP BY b.id`;
  if(activeOnly)sql+=' HAVING COALESCE(SUM(i.remaining_qty),0)>0';
  sql+=' ORDER BY b.stock_date DESC,b.created_at DESC';
  const {results=[]}=await env.DB.prepare(sql).bind(...binds).all();
  if(!results.length)return {ok:true,batches:[]};
  const ids=results.map(x=>x.id),{results:items=[]}=await env.DB.prepare(`SELECT id,batch_id,product_id,variant_id,product_name,initial_qty,remaining_qty,created_at FROM inventory_batch_items WHERE batch_id IN (${ids.map(()=>'?').join(',')}) ORDER BY product_name`).bind(...ids).all(),byBatch=new Map();
  for(const item of items){if(!byBatch.has(item.batch_id))byBatch.set(item.batch_id,[]);byBatch.get(item.batch_id).push({id:item.id,productId:item.product_id,variantId:item.variant_id||null,productName:item.product_name,initialQty:Number(item.initial_qty||0),remainingQty:Number(item.remaining_qty||0)});}
  return {ok:true,batches:results.map(b=>({id:b.id,clientId:b.client_id,storeId:b.store_id||null,name:b.name,stockDate:b.stock_date,note:b.note||'',status:Number(b.total_remaining||0)>0?'active':'depleted',totalInitial:Number(b.total_initial||0),totalRemaining:Number(b.total_remaining||0),createdAt:b.created_at,createdBy:b.created_by||'',items:byBatch.get(b.id)||[]}))};
}
export async function createInventoryBatch(env,{clientId,storeId,name,stockDate,note='',items=[],actor}={}){
  clientId=clean(clientId);storeId=clean(storeId);name=clean(name);stockDate=validDate(stockDate);
  if(!clientId)fail('محتاج clientId',400,'CLIENT_ID_REQUIRED');if(!storeId)fail('اختار المتجر قبل إضافة استوك جديد',400,'STOCK_BATCH_STORE_REQUIRED');if(!name)fail('اكتب اسم/تسمية الاستوك',400,'STOCK_BATCH_NAME_REQUIRED');if(name.length>120)fail('اسم الاستوك طويل جدًا',400,'STOCK_BATCH_NAME_TOO_LONG');
  if(!Array.isArray(items)||!items.length)fail('أضف كمية لمنتج واحد على الأقل',400,'STOCK_BATCH_ITEMS_REQUIRED');if(items.length>500)fail('عدد المنتجات في الاستوك أكبر من المسموح',400,'STOCK_BATCH_TOO_MANY_ITEMS');
  const duplicate=await env.DB.prepare('SELECT id FROM inventory_batches WHERE client_id=? AND store_id=? AND lower(name)=lower(?)').bind(clientId,storeId,name).first();if(duplicate)fail('في استوك بنفس الاسم موجود بالفعل في هذا المتجر',409,'STOCK_BATCH_NAME_EXISTS');
  const merged=new Map();for(const raw of items){const productId=clean(raw?.productId||raw?.product_id),variantId=clean(raw?.variantId||raw?.variant_id)||null,qty=Number(raw?.qty);if(!productId||!Number.isFinite(qty)||qty<=0)continue;const key=`${productId}::${variantId||''}`;const old=merged.get(key);merged.set(key,{productId,variantId,qty:(old?.qty||0)+qty});}
  if(!merged.size)fail('اكتب كميات أكبر من صفر',400,'STOCK_BATCH_QUANTITY_REQUIRED');
  const verified=[];for(const item of merged.values()){
    if(item.variantId){const row=await env.DB.prepare(`SELECT v.id,v.product_id,v.name,v.stock,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id AND p.client_id=v.client_id WHERE v.id=? AND v.product_id=? AND v.client_id=? AND v.store_id=?`).bind(item.variantId,item.productId,clientId,storeId).first();if(!row)fail('أحد متغيرات المنتجات غير موجود في المتجر الحالي',404,'STOCK_BATCH_VARIANT_NOT_FOUND');verified.push({...item,productName:`${row.product_name} — ${row.name}`,oldStock:Number(row.stock||0)});
    }else{const row=await env.DB.prepare('SELECT id,name,stock FROM products WHERE id=? AND client_id=? AND store_id=?').bind(item.productId,clientId,storeId).first();if(!row)fail('أحد المنتجات غير موجود في المتجر الحالي',404,'STOCK_BATCH_PRODUCT_NOT_FOUND');verified.push({...item,productName:row.name,oldStock:Number(row.stock||0)});}
  }
  const id=`BAT-${crypto.randomUUID().slice(0,10).toUpperCase()}`,ts=now(),createdBy=actorName(actor),statements=[env.DB.prepare('INSERT INTO inventory_batches (id,client_id,store_id,name,stock_date,note,status,created_at,created_by) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,clientId,storeId,name,stockDate,clean(note),'active',ts,createdBy)];
  for(const item of verified){const itemId=`BTI-${crypto.randomUUID().slice(0,10).toUpperCase()}`,newStock=item.oldStock+item.qty;statements.push(env.DB.prepare('INSERT INTO inventory_batch_items (id,batch_id,client_id,store_id,product_id,variant_id,product_name,initial_qty,remaining_qty,created_at) VALUES (?,?,?,?,?,?,?,?,?,?)').bind(itemId,id,clientId,storeId,item.productId,item.variantId,item.productName,item.qty,item.qty,ts));if(item.variantId)statements.push(env.DB.prepare('UPDATE product_variants SET stock=COALESCE(stock,0)+? WHERE id=? AND client_id=?').bind(item.qty,item.variantId,clientId));else statements.push(env.DB.prepare('UPDATE products SET stock=COALESCE(stock,0)+? WHERE id=? AND client_id=?').bind(item.qty,item.productId,clientId));statements.push(env.DB.prepare('INSERT INTO stock_log (id,client_id,store_id,product_id,variant_id,product_name,delta,new_stock,note,supplier_id,supplier_name,stock_date,batch_id,batch_name,created_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(`STK-${crypto.randomUUID().slice(0,8).toUpperCase()}`,clientId,storeId,item.productId,item.variantId,item.productName,item.qty,newStock,clean(note)||`إضافة مخزون — ${name}`,null,null,stockDate,id,name,ts,createdBy));}
  await env.DB.batch(statements);return {ok:true,id,name,stockDate,itemCount:verified.length,totalQty:verified.reduce((s,x)=>s+x.qty,0)};
}
export async function assertProductCanDelete(env,{clientId,storeId=null,productId}={}){
  const where=['client_id=?','product_id=?'],binds=[clientId,productId];if(storeId){where.push('store_id=?');binds.push(storeId);}const row=await env.DB.prepare(`SELECT COALESCE(SUM(remaining_qty),0) remaining FROM inventory_batch_items WHERE ${where.join(' AND ')}`).bind(...binds).first(),remaining=Number(row?.remaining||0);if(remaining>0)fail(`المنتج موجود داخل استوك مسمى ولسه فيه ${remaining} قطعة. استهلك أو صفّر الكمية قبل حذف المنتج.`,409,'PRODUCT_HAS_BATCH_STOCK');return true;
}
async function resolveOrderProduct(env,row){
  if(row.product_id)return {productId:row.product_id,variantId:row.variant_id||null};
  const name=clean(row.product);if(!name)fail('الأوردر غير مربوط بمنتج، اربطه بمنتج قبل الشحن',409,'ORDER_PRODUCT_NOT_LINKED');
  const matches=(await env.DB.prepare('SELECT id FROM products WHERE client_id=? AND store_id=? AND trim(name)=trim(?) LIMIT 2').bind(row.client_id,row.store_id,name).all()).results||[];if(matches.length!==1)fail('تعذر تحديد منتج الأوردر داخل المخزون بدقة. اربط الأوردر بمنتج أولًا.',409,'ORDER_PRODUCT_MATCH_AMBIGUOUS');
  await env.DB.prepare('UPDATE orders SET product_id=? WHERE id=? AND client_id=?').bind(matches[0].id,row.id,row.client_id).run();return {productId:matches[0].id,variantId:null};
}
async function allocationRow(env,orderId,clientId){return env.DB.prepare('SELECT * FROM order_stock_allocations WHERE order_id=? AND client_id=?').bind(orderId,clientId).first();}
export async function prepareOrderStockTransition(env,{clientId,storeId,orderId,fromState,toState,stockBatchId,actor}={}){
  if(OUTBOUND_STATES.has(fromState)||!OUTBOUND_STATES.has(toState))return {kind:'none'};
  const order=await env.DB.prepare('SELECT id,client_id,store_id,product,product_id,variant_id,qty FROM orders WHERE id=? AND client_id=?').bind(orderId,clientId).first();if(!order)fail('الأوردر غير موجود',404,'ORDER_NOT_FOUND');storeId=clean(storeId||order.store_id);if(!storeId)fail('الأوردر غير مربوط بمتجر',409,'ORDER_STORE_REQUIRED');
  const existing=await allocationRow(env,orderId,clientId);if(existing?.status==='allocated')return {kind:'none',allocation:existing};
  const batchId=clean(stockBatchId||(existing?.status==='returned'?existing.batch_id:''));if(!batchId)fail('اختار اسم الاستوك الذي سيتم خصم الأوردر منه',409,'STOCK_BATCH_REQUIRED');
  const batch=await env.DB.prepare('SELECT id,name,status FROM inventory_batches WHERE id=? AND client_id=? AND store_id=?').bind(batchId,clientId,storeId).first();if(!batch)fail('الاستوك المختار غير موجود في هذا المتجر',404,'STOCK_BATCH_NOT_FOUND');
  const {productId,variantId}=await resolveOrderProduct(env,order),qty=Math.max(1,Number(order.qty)||1);let item;
  if(variantId)item=await env.DB.prepare('SELECT * FROM inventory_batch_items WHERE batch_id=? AND client_id=? AND store_id=? AND product_id=? AND variant_id=?').bind(batchId,clientId,storeId,productId,variantId).first();else item=await env.DB.prepare('SELECT * FROM inventory_batch_items WHERE batch_id=? AND client_id=? AND store_id=? AND product_id=? AND variant_id IS NULL').bind(batchId,clientId,storeId,productId).first();
  if(!item)fail('الاستوك المختار لا يحتوي على منتج الأوردر المطلوب',409,'STOCK_BATCH_PRODUCT_MISSING');if(Number(item.remaining_qty||0)<qty)fail(`الكمية المتاحة في ${batch.name} هي ${Number(item.remaining_qty||0)} فقط، والأوردر يحتاج ${qty}.`,409,'STOCK_BATCH_INSUFFICIENT');
  const dec=await env.DB.prepare('UPDATE inventory_batch_items SET remaining_qty=remaining_qty-? WHERE id=? AND remaining_qty>=?').bind(qty,item.id,qty).run();if(Number(dec?.meta?.changes||0)!==1)fail('الكمية اتغيرت أثناء التنفيذ. افتح الاستوك من جديد وحاول مرة أخرى.',409,'STOCK_BATCH_CONCURRENT_CHANGE');
  const previous=existing?{...existing}:null,generalAdjusted=fromState!=='returned',logId=generalAdjusted?`STK-${crypto.randomUUID().slice(0,8).toUpperCase()}`:null;
  try{
    let newStock=null;if(generalAdjusted){if(variantId){const p=await env.DB.prepare('SELECT stock FROM product_variants WHERE id=? AND client_id=?').bind(variantId,clientId).first();newStock=Math.max(0,Number(p?.stock||0)-qty);await env.DB.prepare('UPDATE product_variants SET stock=? WHERE id=? AND client_id=?').bind(newStock,variantId,clientId).run();}else{const p=await env.DB.prepare('SELECT stock FROM products WHERE id=? AND client_id=?').bind(productId,clientId).first();newStock=Math.max(0,Number(p?.stock||0)-qty);await env.DB.prepare('UPDATE products SET stock=? WHERE id=? AND client_id=?').bind(newStock,productId,clientId).run();}await env.DB.prepare('INSERT INTO stock_log (id,client_id,store_id,product_id,variant_id,product_name,delta,new_stock,note,supplier_id,supplier_name,stock_date,batch_id,batch_name,created_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(logId,clientId,storeId,productId,variantId,item.product_name,-qty,newStock,`خصم أوردر ${orderId} من ${batch.name}`,null,null,now().slice(0,10),batchId,batch.name,now(),actorName(actor)).run();}
    const allocationId=existing?.order_id||orderId;await env.DB.prepare(`INSERT INTO order_stock_allocations (order_id,client_id,store_id,batch_id,batch_item_id,product_id,variant_id,qty,status,created_at,updated_at,created_by) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(order_id) DO UPDATE SET store_id=excluded.store_id,batch_id=excluded.batch_id,batch_item_id=excluded.batch_item_id,product_id=excluded.product_id,variant_id=excluded.variant_id,qty=excluded.qty,status='allocated',updated_at=excluded.updated_at,created_by=excluded.created_by`).bind(allocationId,clientId,storeId,batchId,item.id,productId,variantId,qty,'allocated',existing?.created_at||now(),now(),actorName(actor)).run();await refreshBatchStatus(env,batchId);return {kind:'allocated',orderId,clientId,storeId,batchId,batchName:batch.name,batchItemId:item.id,productId,variantId,qty,generalAdjusted,logId,previous};
  }catch(error){await env.DB.prepare('UPDATE inventory_batch_items SET remaining_qty=remaining_qty+? WHERE id=?').bind(qty,item.id).run().catch(()=>{});if(generalAdjusted){if(variantId)await env.DB.prepare('UPDATE product_variants SET stock=COALESCE(stock,0)+? WHERE id=?').bind(qty,variantId).run().catch(()=>{});else await env.DB.prepare('UPDATE products SET stock=COALESCE(stock,0)+? WHERE id=?').bind(qty,productId).run().catch(()=>{});if(logId)await env.DB.prepare('DELETE FROM stock_log WHERE id=?').bind(logId).run().catch(()=>{});}await refreshBatchStatus(env,batchId).catch(()=>{});throw error;}
}
export async function rollbackOrderStockTransition(env,token){
  if(!token||token.kind!=='allocated')return;await env.DB.prepare('UPDATE inventory_batch_items SET remaining_qty=remaining_qty+? WHERE id=?').bind(token.qty,token.batchItemId).run().catch(()=>{});if(token.generalAdjusted){if(token.variantId)await env.DB.prepare('UPDATE product_variants SET stock=COALESCE(stock,0)+? WHERE id=?').bind(token.qty,token.variantId).run().catch(()=>{});else await env.DB.prepare('UPDATE products SET stock=COALESCE(stock,0)+? WHERE id=?').bind(token.qty,token.productId).run().catch(()=>{});if(token.logId)await env.DB.prepare('DELETE FROM stock_log WHERE id=?').bind(token.logId).run().catch(()=>{});}if(token.previous){const p=token.previous;await env.DB.prepare('UPDATE order_stock_allocations SET store_id=?,batch_id=?,batch_item_id=?,product_id=?,variant_id=?,qty=?,status=?,updated_at=?,created_by=? WHERE order_id=? AND client_id=?').bind(p.store_id,p.batch_id,p.batch_item_id,p.product_id,p.variant_id,p.qty,p.status,p.updated_at,p.created_by,p.order_id,p.client_id).run().catch(()=>{});}else await env.DB.prepare('DELETE FROM order_stock_allocations WHERE order_id=? AND client_id=?').bind(token.orderId,token.clientId).run().catch(()=>{});await refreshBatchStatus(env,token.batchId).catch(()=>{});
}
export async function finalizeOrderStockTransition(env,{clientId,orderId,fromState,toState}={}){
  if(toState!=='returned'||!OUTBOUND_STATES.has(fromState))return {kind:'none'};const a=await allocationRow(env,orderId,clientId);if(!a||a.status!=='allocated')return {kind:'none'};await env.DB.prepare('UPDATE inventory_batch_items SET remaining_qty=remaining_qty+? WHERE id=?').bind(Number(a.qty)||0,a.batch_item_id).run();await env.DB.prepare("UPDATE order_stock_allocations SET status='returned',updated_at=? WHERE order_id=? AND client_id=?").bind(now(),orderId,clientId).run();await env.DB.prepare("UPDATE inventory_batches SET status='active' WHERE id=?").bind(a.batch_id).run();return {kind:'returned',batchId:a.batch_id,qty:Number(a.qty)||0};
}
